-- Create price_history table
create table public.price_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  price integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster querying by user and time
create index price_history_user_id_created_at_idx on public.price_history (user_id, created_at);

-- RLS
alter table public.price_history enable row level security;

create policy "Price history is viewable by everyone"
  on public.price_history for select
  using ( true );

-- Function to record price change
create or replace function public.record_price_change()
returns trigger
language plpgsql
security definer
as $$
begin
  if (TG_OP = 'INSERT') or (old.price <> new.price) then
    insert into public.price_history (user_id, price)
    values (new.id, new.price);
  end if;
  return new;
end;
$$;

-- Trigger on profiles update
create trigger on_profile_price_change
  after insert or update on public.profiles
  for each row execute procedure public.record_price_change();
