-- Create a table for public profiles
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  tokens integer default 250,
  price integer default 50,
  shares bigint default 1000000,

  primary key (id),
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Create price_history table
create table public.price_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  price integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster querying by user and time
create index price_history_user_id_created_at_idx on public.price_history (user_id, created_at);

-- RLS for price_history
alter table public.price_history enable row level security;

create policy "Price history is viewable by everyone"
  on public.price_history for select
  using ( true );

-- Function to record price change
create or replace function public.record_price_change()
returns trigger
language plpgsql
security definer
as $$
begin
  if (TG_OP = 'INSERT') or (old.price <> new.price) then
    insert into public.price_history (user_id, price)
    values (new.id, new.price);
  end if;
  return new;
end;
$$;

-- Trigger on profiles update/insert
create trigger on_profile_price_change
  after insert or update on public.profiles
  for each row execute procedure public.record_price_change();

-- Set up Realtime!
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.profiles;

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, username, avatar_url, tokens, price, shares)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'username',
    new.raw_user_meta_data->>'avatar_url',
    250,
    50,
    1000000
  );
  return new;
end;
$$;

-- Trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
