-- Add investment related columns to profiles if they don't exist
alter table public.profiles
add column if not exists tokens numeric default 250,
add column if not exists price numeric default 50,
add column if not exists shares numeric default 1000000;

-- Create investments table
create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  investor_id uuid references public.profiles(id) not null,
  target_user_id uuid references public.profiles(id) not null,
  amount_tokens numeric not null,
  amount_shares numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.investments enable row level security;

create policy "Users can view their own investments"
  on public.investments for select
  using (auth.uid() = investor_id);

create policy "Users can insert their own investments"
  on public.investments for insert
  with check (auth.uid() = investor_id);

-- Transaction Function for Investing
create or replace function public.invest_in_user(
  target_user_id uuid,
  invest_amount numeric
)
returns void
language plpgsql
security definer
as $$
declare
  current_user_id uuid;
  user_balance numeric;
  target_price numeric;
  shares_to_buy numeric;
  new_price numeric;
begin
  current_user_id := auth.uid();

  -- Check if user exists and get balance
  select tokens into user_balance
  from public.profiles
  where id = current_user_id;

  if user_balance < invest_amount then
    raise exception 'Insufficient tokens';
  end if;

  -- Get target user details
  select price into target_price
  from public.profiles
  where id = target_user_id;

  -- Default price safety
  if target_price is null or target_price <= 0 then
    target_price := 50;
  end if;

  -- Calculate shares
  shares_to_buy := invest_amount / target_price;

  -- Deduct tokens from investor
  update public.profiles
  set tokens = tokens - invest_amount
  where id = current_user_id;

  -- Logic for price increase:
  -- Simple Linear Model: Price increases by 0.1% of the investment amount per share?
  -- Or just: New Price = Old Price + (Investment / 1000)?
  -- Let's use a simple mechanic: Price increases by 0.5% for every trade, weighted by amount relative to price.
  -- Simpler: Price = Price + (InvestAmount * 0.01)
  new_price := target_price + (invest_amount * 0.005);

  -- Update target user stats
  -- We don't deduct shares from the user per se (unless we treat it as limited supply).
  -- For now, we just track "investments" without reducing a global "shares" pool,
  -- or we assume the pool is infinite/flexible.
  -- However, user requested "shares of that user they would buy".

  update public.profiles
  set price = new_price
  where id = target_user_id;

  -- Record investment
  insert into public.investments (investor_id, target_user_id, amount_tokens, amount_shares)
  values (current_user_id, target_user_id, invest_amount, shares_to_buy);

end;
$$;
