-- Add investment related columns to profiles if they don't exist
alter table public.profiles
add column if not exists tokens numeric default 250,
add column if not exists price numeric default 50,
add column if not exists shares bigint default 1000000,
add column if not exists available_shares bigint default 1000000;

-- Create investments table
create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  investor_id uuid references public.profiles(id) not null,
  target_user_id uuid references public.profiles(id) not null,
  amount_tokens numeric not null,
  amount_shares bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.investments enable row level security;

create policy "Users can view their own investments"
  on public.investments for select
  using (auth.uid() = investor_id);

create policy "Users can insert their own investments"
  on public.investments for insert
  with check (auth.uid() = investor_id);

-- Transaction Function for Investing
create or replace function public.invest_in_user(
  target_user_id uuid,
  invest_amount numeric
)
returns void
language plpgsql
security definer
as $$
declare
  current_user_id uuid;
  user_balance numeric;
  target_price numeric;
  target_available_shares bigint;
  shares_to_buy bigint;
  new_price numeric;
begin
  current_user_id := auth.uid();

  -- Check if user exists and get balance
  select tokens into user_balance
  from public.profiles
  where id = current_user_id;

  if user_balance < invest_amount then
    raise exception 'Insufficient tokens';
  end if;

  -- Get target user details (price and available shares)
  -- Lock the row to prevent race conditions
  select price, available_shares into target_price, target_available_shares
  from public.profiles
  where id = target_user_id
  for update;

  -- Default price safety
  if target_price is null or target_price <= 0 then
    target_price := 50;
  end if;

  -- Calculate shares (truncate to integer)
  shares_to_buy := floor(invest_amount / target_price);

  -- Ensure at least 1 share
  if shares_to_buy < 1 then
     raise exception 'Investment amount too low for 1 share';
  end if;

  -- Check if there are enough shares available
  -- We use coalesce to treat null as 0, though default is 1M
  if coalesce(target_available_shares, 0) < shares_to_buy then
      raise exception 'Not enough shares available. Requested: %, Available: %', shares_to_buy, target_available_shares;
  end if;

  -- Deduct tokens from investor
  update public.profiles
  set tokens = tokens - invest_amount
  where id = current_user_id;

  -- Logic for price increase:
  -- Price increases by 0.5% for every trade, weighted by amount relative to price.
  new_price := target_price + (invest_amount * 0.005);

  -- Update target user stats
  -- Deduct purchased shares from available_shares
  update public.profiles
  set
    price = new_price,
    available_shares = available_shares - shares_to_buy
  where id = target_user_id;

  -- Record investment
  insert into public.investments (investor_id, target_user_id, amount_tokens, amount_shares)
  values (current_user_id, target_user_id, invest_amount, shares_to_buy);

end;
$$;
