-- Create table for search history
create table if not exists search_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  searched_profile_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, searched_profile_id)
);

-- Enable Row Level Security
alter table search_history enable row level security;

-- Policies
-- 1. Users can view their own search history
create policy "Users can view their own search history"
  on search_history for select
  using (auth.uid() = user_id);

-- 2. Users can insert into their own search history
create policy "Users can insert into their own search history"
  on search_history for insert
  with check (auth.uid() = user_id);

-- 3. Users can delete from their own search history
create policy "Users can delete from their own search history"
  on search_history for delete
  using (auth.uid() = user_id);
